# Default language
en:
  languageCode: en-GB
  contentDir: content/en
  title: Anna Yi Leung
  weight: 1

  menu:
    main:
      - name: Home
        url: /
        weight: 10
      - name: Projects
        url: /projects/
        weight: 20
      - name: Publications
        url: /publications/
        weight: 30
      - name: Blog
        url: /blog/
        weight: 40

# Traditional Chinese
zh-hant:
  languageCode: zh-Hant
  contentDir: content/zh_hant
  title: 梁懿
  weight: 2

  menu:
    main:
      - name: 首頁
        url: /
        weight: 10
      - name: 研究與項目
        url: /projects/
        weight: 20
      - name: 教學資源
        url: /teaching/
        weight: 30
      - name: 網誌
        url: /blog/
        weight: 40
