# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    identifier: 071f8e6a
    url: /
    weight: 10
  - name: About
    identifier: about
    url: /about/
    weight: 20
  - name: Projects
    identifier: 05d01025
    url: projects/
    weight: 30
  - name: Publication
    identifier: 4c5a5f97
    url: /#publication
    weight: 40
  - name: Resources
    identifier: resources
    url: /resources
    weight: 50
  - name: Blog
    identifier: blog
    url: /blog/
    weight: 60
